# -------------------------------------------------
# gamehost-Vanish configuration
# DON'T DELETE THOSE VALUES
#
# Author: GameHost
# -------------------------------------------------

# Uprawnienia do vanisha: gh.vanish
# Dostępne zmienne: {PLAYER}, has-vanish nie posiada tej zmiennej.
messages:
    has-vanish: '&8>> &cJestes niewidzialny! &8<<'
    vanish-command-start: '&8>> &cAdministrator &7{PLAYER} &cjest: &7NIEWIDZIALNY&c.'
    vanish-command-end: '&8>> &cAdministrator &7{PLAYER} &cjest: &7WIDZIALNY&c.'
    vanish-join: '&8>> &cAdministrator &7{PLAYER} &cdolaczyl do serwera z wlaczonym vanishem!'

options:
   info-on-actionbar: true # Włącza/wyłącza informacje o włączonym vanishu na ActionBarze.
   item-pickup: true # Włącza/wyłącza podnoszenie itemów gdy ma się włączonego vanisha.