# -------------------------------------------------
# gamehost-RandomTP configuration
# DON'T DELETE THOSE VALUES
#
# Author: GameHost
# -------------------------------------------------

# Lista materiałów: https://helpch.at/docs/1.8/org/bukkit/Material.html

messages:
  teleported: '&aZostales przeteleportowany na koordynaty: &2{X}, {Y}, {Z}&a.' # Komunikat, który pojawi się po przeteleportowaniu gracza na losowe koordynaty
  invalid-location: '&cNie znaleziono bezpiecznego miejsca!' # Komunikat, który się pojawi, gdy RandomTP nie znajdzie bezpiecznego miejsca do przeteleportowania gracza

options:
  min-x: -2000 # Minimalna wartość X
  max-x: 2000 # Maksymalna wartość X
  min-z: -2000 # Minimalnwa wartość Z
  max-z: 2000 # Maksymalna wartość Z
  display-type: 'SUBTITLE' # Gdzie mają pojawiać się komunikaty od RandomTP
  check-location-is-safe: true # Włącza/wyłącza sprawdzanie czy miejsce jest bezpieczne patrz: messages#invalid-location
  distance: 5 # Odległość kratek od której ma łapać graczy grupowe RandomTP
  items: # Itemy, które gracz dostaje po przeteleportowaniu się
    - '64;COOKED_BEEF'