# -------------------------------------------------
# gamehost-AutoMessages configuration
# DON'T DELETE THOSE VALUES
#
# Author: GameHost
# -------------------------------------------------

messages:
  - '&2Example message &c1'
  - '&3Example message &42'

option:
  prefix: '&8[&cINFO&8] '
  suffix: '&a>> '
  delay: 60 # time in seconds