# -------------------------------------------------
# gamehost-Generators configuration
# DON'T DELETE THOSE VALUES
#
# Author: GameHost
# -------------------------------------------------

# Lista materiałów: https://helpch.at/docs/1.8/org/bukkit/Material.html
options:
  material: 'ENDER_STONE' # Materiał z którego ma być stworzona stoniarka
  name: '&6&lStoniarka' # Nazwa stoniarki
  lore: # Opis stoniarki
    - '&aPostaw na ziemi, aby wygenerowal sie kamien!'
  add-recipe: true # Czy ma dodać możliwość craftowania stoniarki z schematu poniżej
  recipe: # Wygląd craftingu: https://i.imgur.com/aVMp4oF.png
    1: 'STONE'
    2: 'STONE'
    3: 'STONE'
    4: 'STONE'
    5: 'PISTON_BASE'
    6: 'STONE'
    7: 'STONE'
    8: 'STONE'
    9: 'STONE'